import { SectionType } from "./types";

// ── Editor field definitions ──────────────────────────────────
// Used by the admin panel to render the correct inputs per section type

export type EditorField =
  | { key: string; label: string; type: "text" }
  | { key: string; label: string; type: "textarea" }
  | { key: string; label: string; type: "richtext" }
  | { key: string; label: string; type: "url" }
  | { key: string; label: string; type: "image" }
  | { key: string; label: string; type: "video" }
  | { key: string; label: string; type: "boolean" }
  | { key: string; label: string; type: "select"; options: string[] }
  | { key: string; label: string; type: "string-array"; itemLabel: string }
  | {
      key: string;
      label: string;
      type: "array";
      itemLabel: string;
      fields: EditorField[];
    };

export interface SectionDefinition {
  type: SectionType;
  label: string;
  defaultContent: Record<string, unknown>;
  editorFields: EditorField[];
  // component is dynamically imported in SectionRenderer
  // to avoid importing all components at registry load time
}

export const SECTION_REGISTRY: Record<SectionType, SectionDefinition> = {
  hero: {
    type: "hero",
    label: "Hero",
    defaultContent: {
      eyebrow: "Join thousands of members nationwide",
      headline: "A National membership built for American women.",
      headline_italic_phrase: "membership",
      subheadline: "Real support. Real savings. Real advocacy. $15 a year.",
      cta_primary_label: "Become a Member",
      cta_primary_url: "/auth/sign-up",
      cta_secondary_label: "Learn More",
      cta_secondary_url: "/about",
      images: [],
      background: "aubergine",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow text", type: "text" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      { key: "headline", label: "Headline", type: "text" },
      {
        key: "headline_italic_phrase",
        label: "Italic phrase in headline",
        type: "text",
      },
      { key: "subheadline", label: "Subheadline", type: "text" },
      { key: "cta_primary_label", label: "Primary CTA label", type: "text" },
      { key: "cta_primary_url", label: "Primary CTA URL", type: "url" },
      {
        key: "cta_secondary_label",
        label: "Secondary CTA label",
        type: "text",
      },
      { key: "cta_secondary_url", label: "Secondary CTA URL", type: "url" },
      { key: "images", label: "Hero image", type: "image" },
    ],
  },

  hero_video: {
    type: "hero_video",
    label: "Hero (Video)",
    defaultContent: {
      eyebrow: "Join thousands of members nationwide",
      headline: "A National membership built for American women.",
      headline_italic_phrase: "membership",
      subheadline: "Real support. Real savings. Real advocacy. $15 a year.",
      cta_primary_label: "Become a Member",
      cta_primary_url: "/auth/sign-up",
      cta_secondary_label: "Learn More",
      cta_secondary_url: "/about",
      video_url: "",
      poster_image_url: "",
      autoplay: true,
      muted: true,
      loop: true,
      plays_inline: true,
      show_controls: false,
      object_fit: "cover",
      background: "aubergine",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow text", type: "text" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      { key: "headline", label: "Headline", type: "text" },
      {
        key: "headline_italic_phrase",
        label: "Italic phrase in headline",
        type: "text",
      },
      { key: "subheadline", label: "Subheadline", type: "text" },
      { key: "cta_primary_label", label: "Primary CTA label", type: "text" },
      { key: "cta_primary_url", label: "Primary CTA URL", type: "url" },
      {
        key: "cta_secondary_label",
        label: "Secondary CTA label",
        type: "text",
      },
      { key: "cta_secondary_url", label: "Secondary CTA URL", type: "url" },
      { key: "video_url", label: "Video (MP4)", type: "video" },
      { key: "poster_image_url", label: "Poster image (optional)", type: "image" },
      { key: "autoplay", label: "Autoplay video", type: "boolean" },
      { key: "muted", label: "Mute video", type: "boolean" },
      { key: "loop", label: "Loop video", type: "boolean" },
      { key: "plays_inline", label: "Plays inline (mobile)", type: "boolean" },
      { key: "show_controls", label: "Show playback controls", type: "boolean" },
      { key: "object_fit", label: "Video fit", type: "select", options: ["cover", "contain"] },
    ],
  },

  stats_bar: {
    type: "stats_bar",
    label: "Stats Bar",
    defaultContent: {
      eyebrow: "Real support. Real results.",
      stats: [
        { value: "0", label: "Active Members" },
        { value: "0", label: "Grants Awarded" },
        { value: "0", label: "States Represented" },
        { value: "0", label: "Perks & Discounts" },
      ],
      background: "wisteria",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      {
        key: "stats",
        label: "Stats",
        type: "array",
        itemLabel: "Stat",
        fields: [
          { key: "value", label: "Value (e.g. 50,000+)", type: "text" },
          { key: "label", label: "Label", type: "text" },
        ],
      },
    ],
  },

  mission_quote: {
    type: "mission_quote",
    label: "Mission Quote",
    defaultContent: {
      eyebrow: "WHO WE ARE",
      quote_text:
        "The National Fund for Women seeks to enhance the quality of life for all American women by championing positive social change and delivering value through resources, information, and advocacy.",
      background: "dove",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      { key: "quote_text", label: "Quote text", type: "textarea" },
    ],
  },

  three_col_features: {
    type: "three_col_features",
    label: "Three Column Features",
    defaultContent: {
      columns: [
        {
          eyebrow: "MICROGRANTS",
          heading: "Direct support when it matters most",
          body: "Financial assistance designed to reduce pressure — not create more of it.",
          bullets: [
            "Assistance for rent, utilities, and childcare",
            "Support for unexpected expenses",
            "Streamlined application designed to feel supportive",
          ],
          cta_label: "Learn More About Microgrants",
          cta_url: "/grants",
          background_image_url: "",
        },
        {
          eyebrow: "MEMBERSHIP SAVINGS",
          heading: "Meaningful savings on what you already buy",
          body: "Exclusive member discounts on everyday essentials.",
          bullets: [
            "Discounts on groceries, gas, and essentials",
            "Exclusive deals on travel and dining",
            "Savings that add up to hundreds per year",
          ],
          cta_label: "Explore Membership Savings",
          cta_url: "/perks",
          background_image_url: "",
        },
        {
          eyebrow: "ZERO DOLLAR STORE",
          heading: "Access essentials without added burden",
          body: "Free items you can claim anytime — no questions, no judgment.",
          bullets: [
            "Hygiene products, household items, and more",
            "No purchase required",
            "Restocked regularly with new items",
          ],
          cta_label: "Visit the Zero Dollar Store",
          cta_url: "/store",
          background_image_url: "",
        },
      ],
    },
    editorFields: [
      {
        key: "columns",
        label: "Columns",
        type: "array",
        itemLabel: "Column",
        fields: [
          { key: "eyebrow", label: "Eyebrow", type: "text" },
          { key: "heading", label: "Heading", type: "text" },
          { key: "body", label: "Body", type: "textarea" },
          {
            key: "background_image_url",
            label: "Background image",
            type: "image",
          },
          {
            key: "bullets",
            label: "Bullet points",
            type: "string-array",
            itemLabel: "Bullet",
          },
          { key: "cta_label", label: "CTA label", type: "text" },
          { key: "cta_url", label: "CTA URL", type: "url" },
        ],
      },
    ],
  },

  split_why_nfw: {
    type: "split_why_nfw",
    label: "Split — Why NFW",
    defaultContent: {
      eyebrow: "WHY NFW",
      headline: "Built for women's real lives.",
      headline_italic_phrase: "real",
      body: "The National Fund for Women is a financially independent membership organization built around women's everyday economic realities. Membership delivers tangible savings and support now — while building durable infrastructure to advocate for women at scale.",
      cta_label: "Become a Member",
      cta_url: "/auth/sign-up",
      pullquote:
        "Women drive the economy, control most household spending, and shoulder the majority of caregiving — yet no permanent institution exists to represent their shared economic interests.",
      background: "dove",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      { key: "headline", label: "Headline", type: "text" },
      { key: "headline_italic_phrase", label: "Italic phrase", type: "text" },
      { key: "body", label: "Body", type: "textarea" },
      { key: "cta_label", label: "CTA label", type: "text" },
      { key: "cta_url", label: "CTA URL", type: "url" },
      { key: "pullquote", label: "Pull quote", type: "textarea" },
    ],
  },

  microgrant_feature: {
    type: "microgrant_feature",
    label: "Microgrant Feature",
    defaultContent: {
      eyebrow: "MICROGRANTS",
      headline: "Real help when life gets hard.",
      headline_italic_phrase: "hard",
      body: "Unexpected expenses happen. Our microgrants provide quick financial support when you need it most — with a simple application designed to feel supportive, not transactional.",
      cta_label: "Learn About Microgrants",
      cta_url: "/grants",
      image_url: "",
      background: "dove",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      { key: "headline", label: "Headline", type: "text" },
      { key: "headline_italic_phrase", label: "Italic phrase", type: "text" },
      { key: "body", label: "Body", type: "textarea" },
      { key: "cta_label", label: "CTA label", type: "text" },
      { key: "cta_url", label: "CTA URL", type: "url" },
      { key: "image_url", label: "Photo", type: "image" },
    ],
  },

  perks_feature: {
    type: "perks_feature",
    label: "Perks Feature + Brand Logos",
    defaultContent: {
      eyebrow: "PERKS & DISCOUNTS",
      headline: "Everyday savings you can feel.",
      headline_italic_phrase: "feel",
      body: "Members get access to thousands of discounts on things you already buy — real savings that make your budget stretch further.",
      cta_label: "Explore Perks & Discounts",
      cta_url: "/perks",
      logo_strip_eyebrow: "BRANDS SHOWING UP FOR WOMEN",
      logos: [],
      background: "wisteria",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      { key: "headline", label: "Headline", type: "text" },
      { key: "headline_italic_phrase", label: "Italic phrase", type: "text" },
      { key: "body", label: "Body", type: "textarea" },
      { key: "cta_label", label: "CTA label", type: "text" },
      { key: "cta_url", label: "CTA URL", type: "url" },
      { key: "logo_strip_eyebrow", label: "Logo strip eyebrow", type: "text" },
      {
        key: "logos",
        label: "Brand logos",
        type: "array",
        itemLabel: "Brand",
        fields: [
          { key: "name", label: "Brand name", type: "text" },
          { key: "image_url", label: "Logo image", type: "image" },
        ],
      },
    ],
  },

  zero_dollar_store_teaser: {
    type: "zero_dollar_store_teaser",
    label: "Zero Dollar Store Teaser",
    defaultContent: {
      eyebrow: "ZERO DOLLAR STORE",
      headline: "Free items you can claim anytime.",
      headline_italic_phrase: "anytime",
      body: "Sometimes you just need a little something to get by. Our Zero Dollar Store lets you claim free essentials whenever you need them — no questions, no judgment.",
      cta_label: "Shop",
      cta_url: "/store",
      products: [],
      background: "dove",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      { key: "headline", label: "Headline", type: "text" },
      { key: "headline_italic_phrase", label: "Italic phrase", type: "text" },
      { key: "body", label: "Body", type: "textarea" },
      { key: "cta_label", label: "CTA label", type: "text" },
      { key: "cta_url", label: "CTA URL", type: "url" },
      {
        key: "products",
        label: "Featured products",
        type: "array",
        itemLabel: "Product",
        fields: [
          { key: "name", label: "Product name", type: "text" },
          { key: "image_url", label: "Product image", type: "image" },
          {
            key: "retail_price",
            label: "Retail price (e.g. From $24)",
            type: "text",
          },
        ],
      },
    ],
  },

  split_everyday: {
    type: "split_everyday",
    label: "Split — Everyday Realities",
    defaultContent: {
      eyebrow: "WOMEN'S ECONOMIC REALITIES",
      headline: "Everyday realities deserve lasting support.",
      headline_italic_phrase: "lasting",
      body: "NFW is built around the real logistics of women's lives — the budgeting, the quiet decisions that keep households running.",
      cta_label: "Join Now",
      cta_url: "/auth/sign-up",
      image_url: "",
      image_side: "left",
      background: "wisteria",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      { key: "headline", label: "Headline", type: "text" },
      { key: "headline_italic_phrase", label: "Italic phrase", type: "text" },
      { key: "body", label: "Body", type: "textarea" },
      { key: "cta_label", label: "CTA label", type: "text" },
      { key: "cta_url", label: "CTA URL", type: "url" },
      { key: "image_url", label: "Image", type: "image" },
      {
        key: "image_side",
        label: "Image side",
        type: "select",
        options: ["left", "right"],
      },
    ],
  },

  testimonials: {
    type: "testimonials",
    label: "Testimonials",
    defaultContent: {
      eyebrow: "MEMBER STORIES",
      heading: "Real women. Real impact.",
      testimonials: [],
      background: "dove",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "heading", label: "Heading", type: "text" },
      {
        key: "background",
        label: "Background",
        type: "select",
        options: ["dove", "aubergine", "wisteria", "blackberry"],
      },
      {
        key: "testimonials",
        label: "Testimonials",
        type: "array",
        itemLabel: "Testimonial",
        fields: [
          { key: "quote", label: "Quote", type: "textarea" },
          { key: "first_name", label: "First name", type: "text" },
          { key: "age", label: "Age", type: "text" },
          { key: "state", label: "State", type: "text" },
        ],
      },
    ],
  },

  faq: {
    type: "faq",
    label: "FAQ",
    defaultContent: {
      eyebrow: "QUESTIONS",
      heading: "Questions? We've got answers.",
      items: [
        {
          question: "How much does membership cost?",
          answer: "NFW membership starts free.",
        },
        {
          question: "How do microgrants work?",
          answer: "Members can apply for microgrants up to $1,000.",
        },
      ],
      background: "aubergine",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      { key: "heading", label: "Heading", type: "text" },
      {
        key: "items",
        label: "FAQ items",
        type: "array",
        itemLabel: "Question",
        fields: [
          { key: "question", label: "Question", type: "text" },
          { key: "answer", label: "Answer", type: "richtext" },
        ],
      },
    ],
  },

  membership_cta: {
    type: "membership_cta",
    label: "Membership CTA",
    defaultContent: {
      eyebrow: "MEMBERSHIP",
      headline: "Membership starts here.",
      headline_italic_phrase: "starts",
      body: "For $15 per year, membership delivers immediate value while building long-term advocacy power. NFW is funded by members and partnerships — not donor cycles.",
      price: "$15",
      price_period: "per year",
      benefits: [
        "Access to grants, exclusive perks & discounts",
        "Eligibility for microgrants — rent, utilities, childcare",
        "Free items from the Zero Dollar Store",
        "Connection to a national community of women",
        "Your membership funds advocacy for women",
      ],
      cta_label: "Start Your Membership",
      cta_url: "/auth/sign-up",
      background: "blackberry",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      { key: "headline", label: "Headline", type: "text" },
      { key: "headline_italic_phrase", label: "Italic phrase", type: "text" },
      { key: "body", label: "Body", type: "textarea" },
      { key: "price", label: "Price", type: "text" },
      { key: "price_period", label: "Price period", type: "text" },
      {
        key: "benefits",
        label: "Benefits",
        type: "array",
        itemLabel: "Benefit",
        fields: [{ key: "text", label: "Benefit text", type: "text" }],
      },
      { key: "cta_label", label: "CTA label", type: "text" },
      { key: "cta_url", label: "CTA URL", type: "url" },
    ],
  },

  right_side_3_features: {
    type: "right_side_3_features",
    label: "Right Side 3 Features",
    defaultContent: {
      eyebrow: "Why we exist",
      headline: "Real support for real life moments",
      body: "Women across America are navigating rising costs, caregiving pressures, wage gaps, and unexpected emergencies — often without a safety net. NFW was created to change that.\n\nWe believe that small, consistent support creates lasting change. Through microgrants, exclusive perks, and a community that truly gets it, we help women find relief — not someday, but today.",
      cta_label: "Join the Community",
      cta_url: "/auth/sign-up",
      background: "dove",
      items: [
        {
          bg: "citrine",
          title: "Celebrate every woman",
          description: "We uplift and affirm all women — through daily life moments, feel-good content, and a community that champions your wins big and small.",
        },
        {
          bg: "lilac",
          title: "Provide relief you can feel",
          description: "From microgrants to perks to the Zero Dollar Store, every benefit is designed to ease real pressure in your everyday life.",
        },
        {
          bg: "powder",
          title: "Champion shared interests",
          description: "NFW advocates for women at the individual level and the collective level — because what's good for one woman is good for all of us.",
        },
      ],
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      { key: "headline", label: "Headline", type: "text" },
      { key: "body", label: "Body (2 paragraphs)", type: "textarea" },
      { key: "cta_label", label: "CTA label", type: "text" },
      { key: "cta_url", label: "CTA URL", type: "url" },
      {
        key: "items",
        label: "Feature items",
        type: "array",
        itemLabel: "Item",
        fields: [
          { key: "bg", label: "Background color", type: "select", options: ["yellow", "green", "blue", "lavender", "citrine", "lilac", "powder"] },
          { key: "title", label: "Title", type: "text" },
          { key: "description", label: "Description", type: "textarea" },
        ],
      },
    ],
  },

  "4_cards": {
    type: "4_cards",
    label: "4 Cards",
    defaultContent: {
      eyebrow: "Our community",
      headline: "Women at every stage of life",
      subheadline: "NFW membership is open to all women 18 and older residing in the United States. We welcome women from all backgrounds and circumstances.",
      cards: [
        {
          color: "yellow",
          age: "18-34",
          title: "Young Women",
          description: "Navigating cost of living, student debt, and building a future in a complicated world.",
        },
        {
          color: "green",
          age: "All ages",
          title: "Moms of Young Kids",
          description: "Balancing childcare costs, limited time, and the daily demands of raising a family.",
        },
        {
          color: "blue",
          age: "Gen X",
          title: "Moms of Older Kids",
          description: "Managing college prep, work-life balance, and caring for loved ones all at once.",
        },
        {
          color: "lavender",
          age: "55+",
          title: "Grandmas and Elders",
          description: "Living on fixed incomes while supporting the next generation and leaving a legacy.",
        },
      ],
      background: "dove",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      { key: "headline", label: "Headline", type: "text" },
      { key: "subheadline", label: "Subheadline", type: "textarea" },
      {
        key: "cards",
        label: "Cards",
        type: "array",
        itemLabel: "Card",
        fields: [
          { key: "color", label: "Color", type: "select", options: ["yellow", "green", "blue", "lavender", "citrine", "lilac", "powder"] },
          { key: "age", label: "Age label", type: "text" },
          { key: "title", label: "Title", type: "text" },
          { key: "description", label: "Description", type: "textarea" },
        ],
      },
    ],
  },

  "3_cards": {
    type: "3_cards",
    label: "3 Cards",
    defaultContent: {
      eyebrow: "What membership includes",
      headline: "Everything you need. Nothing you don't.",
      background: "dove",
      cards: [
        {
          color: "green",
          title: "Microgrants",
          description: "Apply for grants from $100 to $5,000 to cover emergency bills, childcare, medical costs, car repairs, and more. Real people review every application within 48 hours.",
          link: "/grants",
          cta: "Learn about grants",
        },
        {
          color: "blue",
          title: "Perks and Discounts",
          description: "Access 1,000+ member-only deals on groceries, wellness, travel, childcare, and everyday essentials. Members save an average of $500+ per year.",
          link: "/perks/info",
          cta: "Explore perks",
        },
        {
          color: "yellow",
          title: "Zero Dollar Store",
          description: "Claim free essential items whenever you need them — hygiene products, household items, and more. No questions asked, no judgment.",
          link: "/store",
          cta: "Visit the store",
        },
      ],
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      { key: "headline", label: "Headline", type: "text" },
      {
        key: "cards",
        label: "Cards",
        type: "array",
        itemLabel: "Card",
        fields: [
          { key: "color", label: "Color", type: "select", options: ["yellow", "green", "blue", "lavender", "citrine", "lilac", "powder"] },
          { key: "title", label: "Title", type: "text" },
          { key: "description", label: "Description", type: "textarea" },
          { key: "link", label: "Link URL", type: "url" },
          { key: "cta", label: "CTA text", type: "text" },
        ],
      },
    ],
  },

  three_column_stories: {
    type: "three_column_stories",
    label: "3 Column Stories",
    defaultContent: {
      eyebrow: "Picks of the month",
      background: "dove",
      columns: [
        {
          title: "A World With",
          content: "In this episode of A World With, Trinbagonian writer, YouTuber and artist Andrew Sage explores the possibilities of a world with libraries of things.",
          image_url: "",
          link_text: "Listen now",
          link_url: "#",
        },
        {
          title: "Books",
          content: "Healing Justice Ldn on disability justice. A curated reading list of texts and resources about collective care, interdependence, disability justice and building for our changing contexts.",
          image_url: "",
          link_text: "Read more",
          link_url: "#",
        },
        {
          title: "How Do We Grow?",
          content: "Larissa Kennedy speaks with three organisations reshaping climate education and our relationship to environmental justice.",
          image_url: "",
          link_text: "Learn more",
          link_url: "#",
        },
      ],
    },
    editorFields: [
      { key: "eyebrow", label: "Section eyebrow", type: "text" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      {
        key: "columns",
        label: "Columns",
        type: "array",
        itemLabel: "Column",
        fields: [
          { key: "eyebrow", label: "Eyebrow (optional)", type: "text" },
          { key: "title", label: "Title", type: "text" },
          { key: "content", label: "Content", type: "textarea" },
          { key: "image_url", label: "Image URL", type: "image" },
          { key: "link_text", label: "Link text (optional)", type: "text" },
          { key: "link_url", label: "Link URL (optional)", type: "url" },
        ],
      },
    ],
  },

  pricing_hero: {
    type: "pricing_hero",
    label: "Pricing Hero",
    defaultContent: {
      eyebrow: "Membership that gives back",
      headline: "Support that fits your life.",
      subheadline: "Every membership level helps fund the NFW mission. Choose the level that works for you — and unlock benefits that make a real difference in your everyday life.",
      trust_badges: ["Cancel anytime", "Funds go directly to women in need", "Join in minutes"],
      background: "aubergine",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      { key: "headline", label: "Headline", type: "text" },
      { key: "subheadline", label: "Subheadline", type: "textarea" },
      { key: "trust_badges", label: "Trust badges", type: "string-array", itemLabel: "Badge" },
    ],
  },

  pricing_cards: {
    type: "pricing_cards",
    label: "Pricing Cards",
    defaultContent: {
      eyebrow: "Choose your membership",
      headline: "Choose your membership",
      subheadline: "Every tier supports the mission. Upgrade anytime as your needs grow.",
      cards: [
        {
          id: "free",
          name: "Free Member",
          price: "$0",
          period: "forever",
          description: "A warm welcome to the NFW community.",
          features: ["Access to NFW community", "Monthly newsletter", "Event notifications", "Read member articles and resources"],
          highlighted: false,
          badge: null,
          stripe_price_id: "",
        },
        {
          id: "contributing",
          name: "Contributing Member",
          price: "$15",
          period: "/year",
          description: "The most popular way to support NFW and unlock real benefits.",
          features: ["Everything in Free", "Apply for microgrants up to $1,000", "Member perks and discounts platform", "Access to Zero Dollar Store", "Voting rights on NFW initiatives", "Member badge and recognition"],
          highlighted: false,
          badge: "Most Popular",
          stripe_price_id: "",
        },
        {
          id: "founding",
          name: "Founding Member",
          price: "$100",
          period: "/year",
          description: "For women who want to make the biggest impact on the mission.",
          features: ["Everything in Contributing", "Founding member recognition", "Early access to events and programs", "Direct input on NFW initiatives", "Priority grant application review", "Exclusive founding member badge"],
          highlighted: true,
          badge: "Most Impact",
          stripe_price_id: "",
        },
      ],
      checkbox_checked: "green",
      show_buttons: true,
      show_cta: true,
      cta_headline: "Ready to join?",
      cta_body: "Create your free account first, then choose your membership level. It only takes a few minutes.",
      cta_label: "Join Now",
      cta_url: "/auth/sign-up",
      cta_secondary_text: "Already a member?",
      cta_secondary_url: "/auth/login",
      background: "dove",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "headline", label: "Headline", type: "text" },
      { key: "subheadline", label: "Subheadline", type: "textarea" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      { key: "show_buttons", label: "Show Plan Buttons", type: "boolean" },
      {
        key: "cards",
        label: "Plans",
        type: "array",
        itemLabel: "Plan",
        fields: [
          { key: "id", label: "ID", type: "text" },
          { key: "name", label: "Name", type: "text" },
          { key: "price", label: "Price", type: "text" },
          { key: "period", label: "Period", type: "text" },
          { key: "description", label: "Description", type: "textarea" },
          { key: "highlighted", label: "Highlighted (dark card)", type: "boolean" },
          { key: "badge", label: "Badge (optional)", type: "text" },
          { key: "stripe_price_id", label: "Stripe Price ID", type: "text" },
          { key: "features", label: "Features", type: "string-array", itemLabel: "Feature" },
        ],
      },
      { key: "checkbox_checked", label: "Checked color", type: "select", options: ["green", "aubergine", "wisteria", "lilac", "citrine"] },
      { key: "show_cta", label: "Show Bottom CTA", type: "boolean" },
      { key: "cta_headline", label: "CTA Headline", type: "text" },
      { key: "cta_body", label: "CTA Body", type: "textarea" },
      { key: "cta_label", label: "CTA Label", type: "text" },
      { key: "cta_url", label: "CTA URL", type: "url" },
      { key: "cta_secondary_text", label: "Secondary Link Text", type: "text" },
      { key: "cta_secondary_url", label: "Secondary Link URL", type: "url" },
    ],
  },

  pricing_cta_box: {
    type: "pricing_cta_box",
    label: "Pricing CTA Box",
    defaultContent: {
      headline: "Ready to join?",
      body: "Create your free account first, then choose your membership level. It only takes a few minutes.",
      cta_label: "Join Now",
      cta_url: "/auth/sign-up",
      secondary_text: "Already a member?",
      secondary_url: "/auth/login",
      background: "dove",
    },
    editorFields: [
      { key: "headline", label: "Headline", type: "text" },
      { key: "body", label: "Body", type: "textarea" },
      { key: "cta_label", label: "CTA label", type: "text" },
      { key: "cta_url", label: "CTA URL", type: "url" },
      { key: "secondary_text", label: "Secondary link text", type: "text" },
      { key: "secondary_url", label: "Secondary link URL", type: "url" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
    ],
  },

  pricing_comparison: {
    type: "pricing_comparison",
    label: "Pricing Comparison Table",
    defaultContent: {
      eyebrow: "Everything included",
      headline: "Compare all benefits",
      subheadline: "See exactly what's included at every level.",
      column1_label: "Free",
      column2_label: "Contributing",
      column3_label: "Founding",
      checkbox_checked: "green",
      checkbox_unchecked: "blackberry10",
      benefits: [
        { label: "Community access", free: true, contributing: true, founding: true },
        { label: "Monthly newsletter", free: true, contributing: true, founding: true },
        { label: "Event notifications", free: true, contributing: true, founding: true },
        { label: "Articles and resources", free: true, contributing: true, founding: true },
        { label: "Microgrant applications", free: false, contributing: true, founding: true },
        { label: "Perks and discounts platform", free: false, contributing: true, founding: true },
        { label: "Zero Dollar Store access", free: false, contributing: true, founding: true },
        { label: "Voting rights", free: false, contributing: true, founding: true },
        { label: "Member badge", free: false, contributing: true, founding: true },
        { label: "Founding member recognition", free: false, contributing: false, founding: true },
        { label: "Early access to events", free: false, contributing: false, founding: true },
        { label: "Direct input on initiatives", free: false, contributing: false, founding: true },
        { label: "Priority grant review", free: false, contributing: false, founding: true },
      ],
      background: "dove",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "headline", label: "Headline", type: "text" },
      { key: "subheadline", label: "Subheadline", type: "textarea" },
      { key: "column1_label", label: "Column 1 label", type: "text" },
      { key: "column2_label", label: "Column 2 label", type: "text" },
      { key: "column3_label", label: "Column 3 label", type: "text" },
      { key: "checkbox_checked", label: "Checked color", type: "select", options: ["green", "aubergine", "wisteria", "lilac", "citrine"] },
      { key: "checkbox_unchecked", label: "Unchecked color", type: "select", options: ["blackberry10", "blackberry20", "wisteria20"] },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      {
        key: "benefits",
        label: "Benefits",
        type: "array",
        itemLabel: "Benefit",
        fields: [
          { key: "label", label: "Label", type: "text" },
          { key: "free", label: "Free (Column 1)", type: "boolean" },
          { key: "contributing", label: "Contributing (Column 2)", type: "boolean" },
          { key: "founding", label: "Founding (Column 3)", type: "boolean" },
        ],
      },
    ],
  },

  pricing_benefits: {
    type: "pricing_benefits",
    label: "Pricing Benefits",
    defaultContent: {
      eyebrow: "Why it matters",
      headline: "Your membership funds the mission",
      body: "Every dollar from membership goes directly toward funding microgrants, building the perks platform, and advocating for women across the country. When you join, you're not just getting benefits — you're helping another woman get the support she needs.\n\nNFW is built on the belief that small, consistent support creates lasting change. Your membership is part of that.",
      cta_label: "Join the Community",
      cta_url: "/auth/sign-up",
      items: [
        { title: "$2.5M+ in grants awarded", description: "Member dues directly fund microgrants that help women cover emergency bills, childcare, medical costs and more.", icon_color: "green" },
        { title: "50,000+ women supported", description: "A growing community of women across all 50 states finding relief, connection and resources through NFW.", icon_color: "green" },
        { title: "1,000+ perks and discounts", description: "Members save an average of $500+ per year on everyday essentials through the NFW perks platform.", icon_color: "green" },
      ],
      background: "dove",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "headline", label: "Headline", type: "text" },
      { key: "body", label: "Body", type: "textarea" },
      { key: "cta_label", label: "CTA label", type: "text" },
      { key: "cta_url", label: "CTA URL", type: "url" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      {
        key: "items",
        label: "Benefits",
        type: "array",
        itemLabel: "Benefit",
        fields: [
          { key: "title", label: "Title", type: "text" },
          { key: "description", label: "Description", type: "textarea" },
          { key: "icon_color", label: "Icon color", type: "select", options: ["green", "yellow", "blue", "lilac"] },
        ],
      },
    ],
  },

  pricing_final_cta: {
    type: "pricing_final_cta",
    label: "Pricing Final CTA",
    defaultContent: {
      headline: "Ready to feel supported?",
      subheadline: "Join thousands of women who have already found relief, connection and real support through NFW. Your journey starts here.",
      items: [
        { title: "Microgrants", sub: "Up to $1,000 in support", icon_color: "green" },
        { title: "Exclusive Perks", sub: "Save $500+ per year", icon_color: "green" },
        { title: "Community", sub: "50,000+ women strong", icon_color: "green" },
      ],
      cta_label: "Become a Member Today",
      cta_url: "/auth/sign-up",
      footnote: "Join in minutes. No credit card required to browse.",
      background: "aubergine",
    },
    editorFields: [
      { key: "headline", label: "Headline", type: "text" },
      { key: "subheadline", label: "Subheadline", type: "textarea" },
      { key: "cta_label", label: "CTA label", type: "text" },
      { key: "cta_url", label: "CTA URL", type: "url" },
      { key: "footnote", label: "Footnote", type: "text" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      {
        key: "items",
        label: "Items",
        type: "array",
        itemLabel: "Item",
        fields: [
          { key: "title", label: "Title", type: "text" },
          { key: "sub", label: "Subtitle", type: "text" },
          { key: "icon_color", label: "Icon color", type: "select", options: ["green", "yellow", "blue", "lilac"] },
        ],
      },
    ],
  },

  how_it_works: {
    type: "how_it_works",
    label: "How It Works (3 Steps)",
    defaultContent: {
      eyebrow: "Secure, simple and smart",
      headline: "How it works",
      subheadline: "Getting support should feel simple.",
      steps: [
        { icon: "FileText", icon_color: "green", title: "Apply in a few minutes", description: "Share the basics of your situation in a short, simple form. No lengthy paperwork." },
        { icon: "Eye", icon_color: "yellow", title: "We review your request", description: "A real person looks at your application with care. Most reviews happen within 48 hours." },
        { icon: "Banknote", icon_color: "blue", title: "Funds are sent securely", description: "If approved, your grant is delivered by bank transfer or digital wallet — fast." },
      ],
      background: "wisteria",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "headline", label: "Headline", type: "text" },
      { key: "subheadline", label: "Subheadline", type: "textarea" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      {
        key: "steps",
        label: "Steps",
        type: "array",
        itemLabel: "Step",
        fields: [
          { key: "icon", label: "Icon", type: "select", options: ["FileText", "Eye", "Clock", "Banknote", "DollarSign", "Coins", "CheckCircle", "CircleCheck", "Gift", "Package", "ShieldCheck", "ClipboardList", "Send", "Search", "CreditCard", "UserCheck", "Rocket", "Calendar", "MapPin", "HandHeart", "Sparkles", "Star", "Zap", "Tag", "Bookmark", "CalendarCheck", "Lock", "Shield"] },
          { key: "icon_color", label: "Icon color", type: "select", options: ["green", "yellow", "blue", "lilac"] },
          { key: "title", label: "Title", type: "text" },
          { key: "description", label: "Description", type: "textarea" },
        ],
      },
    ],
  },

  benefits_checkmarks: {
    type: "benefits_checkmarks",
    label: "Benefits with Checkmarks",
    defaultContent: {
      eyebrow: "Made for real life",
      headline: "Why members love them",
      body: "Perks are built to make everyday life easier. Members use them to save money on the things they already buy, discover helpful offers and find small moments of relief throughout the week.",
      benefits: [
        { check_color: "green", title: "Real savings you can feel", description: "Many members save more than their membership cost. Discounts on essentials help your budget stretch further." },
        { check_color: "yellow", title: "Helpful for everyday life", description: "Perks cover things you use every day like groceries, health items and childcare bringing quick relief when life feels busy." },
        { check_color: "blue", title: "New deals added often", description: "Fresh offers are added throughout the month so there is always something helpful to claim and enjoy." },
      ],
      cta_label: "Become a Member",
      cta_url: "/auth/sign-up",
      background: "dove",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "headline", label: "Headline", type: "text" },
      { key: "body", label: "Body", type: "textarea" },
      { key: "cta_label", label: "CTA label", type: "text" },
      { key: "cta_url", label: "CTA URL", type: "url" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      {
        key: "benefits",
        label: "Benefits",
        type: "array",
        itemLabel: "Benefit",
        fields: [
          { key: "check_color", label: "Check color", type: "select", options: ["green", "yellow", "blue", "lilac"] },
          { key: "title", label: "Title", type: "text" },
          { key: "description", label: "Description", type: "textarea" },
        ],
      },
    ],
  },

  grants_hero: {
    type: "grants_hero",
    label: "Grants Hero",
    defaultContent: {
      eyebrow: "Now Accepting Applications",
      headline: "For the moments that matter.",
      subheadline: "Microgrants from $100 to $5,000 for bills, essentials, and unexpected costs. Simple to apply. Fast to receive.",
      cta_label: "Apply Today",
      cta_url: "/grants/apply",
      secondary_cta_label: "Become a Member",
      secondary_cta_url: "/auth/sign-up",
      trust_badges: ["Real people review every application", "Decisions within 48 hours", "50 states served"],
      image_url: "/images/microgrants-help.jpg",
      stat_value: "$2.5M+",
      stat_label: "Grants awarded to women nationwide",
      secondary_stat_value: "$100 – $5,000",
      secondary_stat_label: "per grant",
      background: "dove",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      { key: "headline", label: "Headline", type: "text" },
      { key: "subheadline", label: "Subheadline", type: "textarea" },
      { key: "cta_label", label: "Primary CTA label", type: "text" },
      { key: "cta_url", label: "Primary CTA URL", type: "url" },
      { key: "secondary_cta_label", label: "Secondary CTA label", type: "text" },
      { key: "secondary_cta_url", label: "Secondary CTA URL", type: "url" },
      { key: "trust_badges", label: "Trust badges", type: "string-array", itemLabel: "Badge" },
      { key: "image_url", label: "Image URL", type: "image" },
      { key: "stat_value", label: "Stat value", type: "text" },
      { key: "stat_label", label: "Stat label", type: "text" },
      { key: "secondary_stat_value", label: "Secondary stat value", type: "text" },
      { key: "secondary_stat_label", label: "Secondary stat label", type: "text" },
    ],
  },

  grants_grid: {
    type: "grants_grid",
    label: "Grants Grid",
    defaultContent: {
      eyebrow: "",
      headline: "Grants that help with real-life needs",
      subheadline: "Explore microgrants that cover emergencies, essentials, and the moments when life gets heavy.",
      cta_label: "Apply Today",
      cta_url: "/grants/apply",
      cards: [
        { title: "$750 Healthcare Support", description: "Supports medical appointments, prescriptions, or urgent health costs that pop up when you least need them.", closing: "Closing Dec 31, 2026", image_url: "/images/microgrants-help.jpg" },
        { title: "$100 Rainy Day Fund", description: "Quick relief for unexpected expenses — a bill, a co-pay, or anything that caught you off guard this month.", closing: "Closing Dec 31, 2026", image_url: "/images/microgrants-help.jpg" },
        { title: "$300 Essentials Grant", description: "Helps with groceries, home basics, or a week's worth of essentials during a tight month.", closing: "Closing Feb 8, 2026", image_url: "/images/microgrants-help.jpg" },
        { title: "$5,000 Small Business Starter", description: "Provides seed funding for supplies, tools, or equipment to grow or launch a small business idea.", closing: "Closing Jan 11, 2027", image_url: "/images/microgrants-help.jpg" },
        { title: "$2,500 Mobility and Work Grant", description: "Helps with transportation, job training, certifications, or anything that moves you forward.", closing: "Closing Jan 3, 2027", image_url: "/images/microgrants-help.jpg" },
        { title: "$500 Childcare Support", description: "Covers childcare, school fees, or after-school care so it's easier to work or keep appointments.", closing: "Closing Jan 11, 2027", image_url: "/images/microgrants-help.jpg" },
      ],
      background: "dove",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "headline", label: "Headline", type: "text" },
      { key: "subheadline", label: "Subheadline", type: "textarea" },
      { key: "cta_label", label: "CTA label", type: "text" },
      { key: "cta_url", label: "CTA URL", type: "url" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      {
        key: "cards",
        label: "Grants",
        type: "array",
        itemLabel: "Grant",
        fields: [
          { key: "title", label: "Title", type: "text" },
          { key: "description", label: "Description", type: "textarea" },
          { key: "closing", label: "Closing date", type: "text" },
          { key: "image_url", label: "Image URL", type: "image" },
        ],
      },
    ],
  },

  grant_amount_cards: {
    type: "grant_amount_cards",
    label: "Grant Amount Cards",
    defaultContent: {
      eyebrow: "Grant Amounts",
      headline: "How much you can receive",
      subheadline: "Microgrants come in different amounts depending on your need — all designed to give you quick, meaningful relief.",
      cta_label: "Apply Today",
      cta_url: "/grants/apply",
      items: [
        { range: "$100 – $500", label: "Emergency Grants", description: "Urgent needs like utility payments, transit to work, childcare gaps, or groceries.", bg_tint: "powder" },
        { range: "$500 – $2,500", label: "Stability Grants", description: "Housing deposits, certifications, or medical expenses not covered by insurance.", bg_tint: "citrine" },
        { range: "$2,500 – $5,000", label: "Business and Growth Grants", description: "A boost to help you start or grow a small business idea with real potential.", bg_tint: "lilac" },
      ],
      background: "dove",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "headline", label: "Headline", type: "text" },
      { key: "subheadline", label: "Subheadline", type: "textarea" },
      { key: "cta_label", label: "CTA label", type: "text" },
      { key: "cta_url", label: "CTA URL", type: "url" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      {
        key: "items",
        label: "Amounts",
        type: "array",
        itemLabel: "Amount",
        fields: [
          { key: "range", label: "Range", type: "text" },
          { key: "label", label: "Label", type: "text" },
          { key: "description", label: "Description", type: "textarea" },
          { key: "bg_tint", label: "Background tint", type: "select", options: ["powder", "citrine", "lilac"] },
        ],
      },
    ],
  },

  success_stories: {
    type: "success_stories",
    label: "Success Stories",
    defaultContent: {
      eyebrow: "Small wins matter",
      headline: "Success Stories and Everyday Wins",
      subheadline: "Feel-good moments from women supporting women.",
      cta_label: "See all stories",
      cta_url: "/articles",
      cards: [
        { category: "Everyday Expense", bg_tint: "citrine", title: "A microgrant helped me fix my car and get back to work", image_url: "/images/microgrants-help.jpg" },
        { category: "Parenting", bg_tint: "powder", title: "Covering an unexpected bill gave me room to breathe", image_url: "/images/microgrants-help.jpg" },
        { category: "Medical Support", bg_tint: "lilac", title: "Getting support for medical costs eased so much stress", image_url: "/images/microgrants-help.jpg" },
      ],
      background: "dove",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "headline", label: "Headline", type: "text" },
      { key: "subheadline", label: "Subheadline", type: "textarea" },
      { key: "cta_label", label: "CTA label", type: "text" },
      { key: "cta_url", label: "CTA URL", type: "url" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      {
        key: "cards",
        label: "Stories",
        type: "array",
        itemLabel: "Story",
        fields: [
          { key: "category", label: "Category", type: "text" },
          { key: "bg_tint", label: "Badge tint", type: "select", options: ["citrine", "powder", "lilac"] },
          { key: "title", label: "Title", type: "text" },
          { key: "image_url", label: "Image URL", type: "image" },
        ],
      },
    ],
  },

  perks_store_grid: {
    type: "perks_store_grid",
    label: "Perks/Store Grid",
    defaultContent: {
      eyebrow: "1,000+ member-only deals available now",
      headline: "Everyday savings you can feel",
      subheadline: "Members get access to fresh deals on things you already spend money on.",
      cta_label: "Browse All Perks",
      cta_url: "/perks",
      cards: [
        { category: "Insurance", name: "Fetch Pet Insurance", description: "5% off monthly premiums", color: "yellow" },
        { category: "Travel", name: "Zipcar Car Sharing", description: "25% off annual membership", color: "blue" },
        { category: "Health & Wellness", name: "Calm & Co.", description: "20% off mindfulness membership", color: "green" },
        { category: "Health & Wellness", name: "CVS Pharmacy", description: "Savings & Discounts by Optum Rx", color: "green" },
        { category: "Entertainment", name: "Ancestry", description: "50% off 1 year subscription", color: "lavender" },
        { category: "Shopping & Groceries", name: "bistroMD", description: "25% off plus Free Shipping on your first order", color: "yellow" },
      ],
      background: "dove",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "headline", label: "Headline", type: "text" },
      { key: "subheadline", label: "Subheadline", type: "textarea" },
      { key: "cta_label", label: "CTA label", type: "text" },
      { key: "cta_url", label: "CTA URL", type: "url" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      {
        key: "cards",
        label: "Items",
        type: "array",
        itemLabel: "Item",
        fields: [
          { key: "category", label: "Category", type: "text" },
          { key: "name", label: "Name", type: "text" },
          { key: "description", label: "Description", type: "textarea" },
          { key: "color", label: "Color", type: "select", options: ["yellow", "green", "blue", "lavender", "citrine", "lilac", "powder"] },
        ],
      },
    ],
  },

  testimonials_grid: {
    type: "testimonials_grid",
    label: "Testimonials Grid",
    defaultContent: {
      eyebrow: "What members are saying",
      headline: "Real stories from our community",
      subheadline: "These everyday moments show how perks, savings and small bits of support can make life feel a little lighter.",
      cards: [
        { quote: "I applied for a microgrant and within 48 hours I had the funds. It was such a relief.", name: "Sarah M.", role: "Member since 2023", avatar_color: "citrine" },
        { quote: "The perks program has saved me over $400 this year alone. It's been a game-changer.", name: "Jennifer L.", role: "Founding Member", avatar_color: "green" },
        { quote: "Knowing there's a community behind me makes all the difference. NFW feels like home.", name: "Maria R.", role: "Member since 2024", avatar_color: "blue" },
        { quote: "I love that I can claim free essentials from the Zero Dollar Store whenever I need to.", name: "Ashley T.", role: "Contributing Member", avatar_color: "lavender" },
        { quote: "The grants helped me cover my car repairs so I could get back to work. So grateful.", name: "Demi W.", role: "Member since 2023", avatar_color: "lilac" },
        { quote: "Being part of NFW means having people in your corner. It's more than a membership.", name: "Nicole B.", role: "Founding Member", avatar_color: "powder" },
      ],
      background: "dove",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "headline", label: "Headline", type: "text" },
      { key: "subheadline", label: "Subheadline", type: "textarea" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
      {
        key: "cards",
        label: "Testimonials",
        type: "array",
        itemLabel: "Testimonial",
        fields: [
          { key: "quote", label: "Quote", type: "textarea" },
          { key: "name", label: "Name", type: "text" },
          { key: "role", label: "Role/Member since", type: "text" },
          { key: "avatar_color", label: "Avatar color", type: "select", options: ["yellow", "green", "blue", "lavender", "citrine", "lilac", "powder"] },
        ],
      },
    ],
  },

  member_celebration_grid: {
    type: "member_celebration_grid",
    label: "Member Celebration Grid",
    defaultContent: {
      eyebrow: "",
      headline: "Small wins matter. Let's celebrate yours.",
      body: "Stories, joy, and tiny moments of relief. Every day.",
      cta_label: "Become a Member",
      cta_url: "/auth/sign-up",
      image1_url: "/images/member-1.jpg",
      image2_url: "/images/member-2.jpg",
      image3_url: "/images/member-3.jpg",
      image4_url: "/images/member-4.jpg",
      background: "dove",
    },
    editorFields: [
      { key: "eyebrow", label: "Eyebrow", type: "text" },
      { key: "headline", label: "Headline", type: "text" },
      { key: "body", label: "Body", type: "textarea" },
      { key: "cta_label", label: "CTA label", type: "text" },
      { key: "cta_url", label: "CTA URL", type: "url" },
      { key: "image1_url", label: "Image 1 URL", type: "image" },
      { key: "image2_url", label: "Image 2 URL", type: "image" },
      { key: "image3_url", label: "Image 3 URL", type: "image" },
      { key: "image4_url", label: "Image 4 URL", type: "image" },
      { key: "background", label: "Background", type: "select", options: ["dove", "aubergine", "wisteria", "lilac", "blackberry"] },
    ],
  },

  stacked_features: {
    type: "stacked_features",
    label: "Stacked Features",
    defaultContent: {
      columns: [
        {
          image_url: "",
          image_overlay: true,
          bg_color: "dark_purple",
          eyebrow: "Community",
          heading: "Built on Connection",
          body: "NFW brings people together through shared experiences, mutual support, and a commitment to helping each other thrive.",
          bullets: [],
          cta_label: "",
          cta_url: "",
        },
        {
          image_url: "",
          image_overlay: true,
          bg_color: "medium_lavender",
          eyebrow: "Impact",
          heading: "Real Support",
          body: "From microgrants to everyday perks, we provide tangible resources that make a difference in people's daily lives.",
          bullets: [],
          cta_label: "",
          cta_url: "",
        },
        {
          image_url: "",
          image_overlay: true,
          bg_color: "soft_blue",
          eyebrow: "Growth",
          heading: "Growing Together",
          body: "Our community is built on the belief that when we uplift each other, everyone benefits and grows.",
          bullets: [],
          cta_label: "",
          cta_url: "",
        },
      ],
    },
    editorFields: [
      {
        key: "columns",
        label: "Columns",
        type: "array",
        itemLabel: "Column",
        fields: [
          { key: "image_url", label: "Image URL", type: "image" },
          { key: "image_overlay", label: "Dark overlay on image", type: "boolean" },
          { key: "bg_color", label: "Background color", type: "select", options: ["yellow", "green", "blue", "lavender", "citrine", "lilac", "powder", "dark_purple", "medium_lavender", "soft_blue"] },
          { key: "eyebrow", label: "Eyebrow", type: "text" },
          { key: "heading", label: "Heading", type: "text" },
          { key: "body", label: "Body", type: "textarea" },
          { key: "bullets", label: "Bullets", type: "string-array", itemLabel: "Bullet" },
          { key: "cta_label", label: "CTA label", type: "text" },
          { key: "cta_url", label: "CTA URL", type: "url" },
        ],
      },
    ],
  },
};
