import { NextResponse } from "next/server";

const FACETS = {
  cuisine: [
    { key: "cuisine:afghan", label: "Afghan" },
    { key: "cuisine:african", label: "African" },
    { key: "cuisine:american", label: "American" },
    { key: "cuisine:argentine", label: "Argentine" },
    { key: "cuisine:armenian", label: "Armenian" },
    { key: "cuisine:asian_fusion", label: "Asian Fusion" },
    { key: "cuisine:bagels", label: "Bagels" },
    { key: "cuisine:barbeque", label: "Barbeque" },
    { key: "cuisine:beer_wine_spirits", label: "Beer, Wine & Spirits" },
    { key: "cuisine:brazilian", label: "Brazilian" },
    { key: "cuisine:british", label: "British" },
    { key: "cuisine:burgers", label: "Burgers" },
    { key: "cuisine:cajun_creole", label: "Cajun/Creole" },
    { key: "cuisine:canadian", label: "Canadian" },
    { key: "cuisine:caribbean", label: "Caribbean" },
    { key: "cuisine:chicken", label: "Chicken" },
    { key: "cuisine:chicken_wings", label: "Chicken Wings" },
    { key: "cuisine:chinese", label: "Chinese" },
    { key: "cuisine:coffee_tea", label: "Coffee & Tea" },
    { key: "cuisine:colombian", label: "Colombian" },
    { key: "cuisine:cuban", label: "Cuban" },
    { key: "cuisine:desserts", label: "Desserts" },
    { key: "cuisine:donuts", label: "Donuts" },
    { key: "cuisine:eastern_european", label: "Eastern European" },
    { key: "cuisine:ethiopian", label: "Ethiopian" },
    { key: "cuisine:filipino", label: "Filipino" },
    { key: "cuisine:fish_chips", label: "Fish & Chips" },
    { key: "cuisine:fondue", label: "Fondue" },
    { key: "cuisine:french", label: "French" },
    { key: "cuisine:frozen_yogurt", label: "Frozen Yogurt" },
    { key: "cuisine:german", label: "German" },
    { key: "cuisine:greek", label: "Greek" },
    { key: "cuisine:halal", label: "Halal" },
    { key: "cuisine:hawaiian", label: "Hawaiian" },
    { key: "cuisine:himalyan", label: "Himalayan" },
    { key: "cuisine:hot_dog", label: "Hot Dog" },
    { key: "cuisine:ice_cream", label: "Ice Cream" },
    { key: "cuisine:indian", label: "Indian" },
    { key: "cuisine:indonesian", label: "Indonesian" },
    { key: "cuisine:irish", label: "Irish" },
    { key: "cuisine:italian", label: "Italian" },
    { key: "cuisine:japanese", label: "Japanese" },
    { key: "cuisine:korean", label: "Korean" },
    { key: "cuisine:kosher", label: "Kosher" },
    { key: "cuisine:latin", label: "Latin" },
    { key: "cuisine:lebanese", label: "Lebanese" },
    { key: "cuisine:mediterranean", label: "Mediterranean" },
    { key: "cuisine:mexican", label: "Mexican" },
    { key: "cuisine:middle_eastern", label: "Middle Eastern" },
    { key: "cuisine:mongolian", label: "Mongolian" },
    { key: "cuisine:moroccan", label: "Moroccan" },
    { key: "cuisine:pakistani", label: "Pakistani" },
    { key: "cuisine:persian_iranian", label: "Persian/Iranian" },
    { key: "cuisine:peruvian", label: "Peruvian" },
    { key: "cuisine:pita", label: "Pita" },
    { key: "cuisine:pizza", label: "Pizza" },
    { key: "cuisine:portuguese", label: "Portuguese" },
    { key: "cuisine:pretzels", label: "Pretzels" },
    { key: "cuisine:puerto_rican", label: "Puerto Rican" },
    { key: "cuisine:russian", label: "Russian" },
    { key: "cuisine:salad", label: "Salad" },
    { key: "cuisine:sandwiches", label: "Sandwiches" },
    { key: "cuisine:seafood", label: "Seafood" },
    { key: "cuisine:smoothies", label: "Smoothies" },
    { key: "cuisine:soul_food", label: "Soul Food" },
    { key: "cuisine:soup", label: "Soup" },
    { key: "cuisine:southern", label: "Southern" },
    { key: "cuisine:spanish", label: "Spanish" },
    { key: "cuisine:steakhouses", label: "Steakhouses" },
    { key: "cuisine:sushi", label: "Sushi" },
    { key: "cuisine:tapas", label: "Tapas" },
    { key: "cuisine:tex_mex", label: "Tex-Mex" },
    { key: "cuisine:thai", label: "Thai" },
    { key: "cuisine:turkish", label: "Turkish" },
    { key: "cuisine:vegetarian", label: "Vegetarian" },
    { key: "cuisine:vietnamese", label: "Vietnamese" },
  ],
  activities: [
    { key: "activities:aerial_adventure_parks", label: "Aerial Adventure Parks" },
    { key: "activities:air_tours", label: "Air Tours" },
    { key: "activities:amusement_parks", label: "Amusement Parks" },
    { key: "activities:aquariums", label: "Aquariums" },
    { key: "activities:arcades_and_games", label: "Arcades & Games" },
    { key: "activities:art_classes", label: "Art Classes" },
    { key: "activities:art_galleries", label: "Art Galleries" },
    { key: "activities:atvs_and_offroading", label: "ATVs & Offroading" },
    { key: "activities:ballets_and_operas", label: "Ballets & Operas" },
    { key: "activities:balloon_rides", label: "Balloon Rides" },
    { key: "activities:baseball", label: "Baseball" },
    { key: "activities:basketball", label: "Basketball" },
    { key: "activities:batting_cages", label: "Batting Cages" },
    { key: "activities:bicycling", label: "Bicycling" },
    { key: "activities:billiards", label: "Billiards" },
    { key: "activities:boat_rentals", label: "Boat Rentals" },
    { key: "activities:boat_tours", label: "Boat Tours" },
    { key: "activities:bowling", label: "Bowling" },
    { key: "activities:canoeing_and_kayacking", label: "Canoeing & Kayacking" },
    { key: "activities:choirs", label: "Choirs" },
    { key: "activities:circus_and_fairs", label: "Circus & Fairs" },
    { key: "activities:comedy_clubs", label: "Comedy Clubs" },
    { key: "activities:concerts", label: "Concerts" },
    { key: "activities:cooking", label: "Cooking" },
    { key: "activities:cross_country_ski_areas", label: "Cross Country Ski Areas" },
    { key: "activities:dancing", label: "Dancing" },
    { key: "activities:day_camps", label: "Day Camps" },
    { key: "activities:dinner_theaters", label: "Dinner Theaters" },
    { key: "activities:diving", label: "Diving" },
    { key: "activities:festivals", label: "Festivals" },
    { key: "activities:fishing", label: "Fishing" },
    { key: "activities:flight_schools", label: "Flight Schools" },
    { key: "activities:football", label: "Football" },
    { key: "activities:fun_centers", label: "Fun Centers" },
    { key: "activities:gardens", label: "Gardens" },
    { key: "activities:go_karts", label: "Go Karts" },
    { key: "activities:golf_courses", label: "Golf Courses" },
    { key: "activities:golf_lessons", label: "Golf Lessons" },
    { key: "activities:gymnastics", label: "Gymnastics" },
    { key: "activities:haunted_houses", label: "Haunted Houses" },
    { key: "activities:hiking_camping", label: "Hiking & Camping" },
    { key: "activities:historical_sites", label: "Historical Sites" },
    { key: "activities:hockey", label: "Hockey" },
    { key: "activities:horseback_riding", label: "Horseback Riding" },
    { key: "activities:hunting", label: "Hunting" },
    { key: "activities:jet_skis", label: "Jet Skis" },
    { key: "activities:laser_tag", label: "Laser Tag" },
    { key: "activities:martial_arts", label: "Martial Arts" },
    { key: "activities:mini_golf", label: "Mini Golf" },
    { key: "activities:motorcycles_and_scooters", label: "Motorcycles & Scooters" },
    { key: "activities:movie_theatres", label: "Movie Theatres" },
    { key: "activities:museums", label: "Museums" },
    { key: "activities:music_classes", label: "Music Classes" },
    { key: "activities:orchestras_symphonies", label: "Orchestras & Symphonies" },
    { key: "activities:paddleboarding", label: "Paddleboarding" },
    { key: "activities:paintball", label: "Paintball" },
    { key: "activities:parks_and_nature", label: "Parks & Nature" },
    { key: "activities:planetariums", label: "Planetariums" },
    { key: "activities:psychics_and_astrologers", label: "Psychics & Astrologers" },
    { key: "activities:puppets", label: "Puppets" },
    { key: "activities:race_car_tracks", label: "Race Car Tracks" },
    { key: "activities:rafting", label: "Rafting" },
    { key: "activities:rail_tours", label: "Rail Tours" },
    { key: "activities:rock_climbing", label: "Rock Climbing" },
    { key: "activities:rv_rentals", label: "RV Rentals" },
    { key: "activities:segways", label: "Segways" },
    { key: "activities:shooting_ranges", label: "Shooting Ranges" },
    { key: "activities:skating", label: "Skating" },
    { key: "activities:ski_and_snowboard_areas", label: "Ski & Snowboard Areas" },
    { key: "activities:ski_lessons", label: "Ski Lessons" },
    { key: "activities:ski_rentals", label: "Ski Rentals" },
    { key: "activities:skydiving_and_parasailing", label: "Skydiving & Parasailing" },
    { key: "activities:soccer", label: "Soccer" },
    { key: "activities:sports_camps", label: "Sports Camps" },
    { key: "activities:sports_teams", label: "Sports Teams" },
    { key: "activities:stadiums_and_arenas", label: "Stadiums & Arenas" },
    { key: "activities:surfing", label: "Surfing" },
    { key: "activities:swimming", label: "Swimming" },
    { key: "activities:tennis", label: "Tennis" },
    { key: "activities:theatre_performances", label: "Theatre Performances" },
    { key: "activities:tours", label: "Tours" },
    { key: "activities:volleyball", label: "Volleyball" },
    { key: "activities:water_parks", label: "Water Parks" },
    { key: "activities:whale_and_dolphin_watching", label: "Whale & Dolphin Watching" },
    { key: "activities:yoga_pilates", label: "Yoga & Pilates" },
    { key: "activities:zoos", label: "Zoos" },
  ],
  storetype: [
    { key: "storetype:bakeries", label: "Bakeries" },
    { key: "storetype:bars", label: "Bars" },
    { key: "storetype:bistros", label: "Bistros" },
    { key: "storetype:breakfast_brunch", label: "Breakfast & Brunch" },
    { key: "storetype:breweries", label: "Breweries" },
    { key: "storetype:buffet", label: "Buffet" },
    { key: "storetype:cafes", label: "Cafes" },
    { key: "storetype:candy", label: "Candy" },
    { key: "storetype:catering", label: "Catering" },
    { key: "storetype:coffee_shops", label: "Coffee Shops" },
    { key: "storetype:concessions_snacks", label: "Concessions & Snacks" },
    { key: "storetype:convenience_stores", label: "Convenience Stores" },
    { key: "storetype:delis", label: "Delis" },
    { key: "storetype:diners", label: "Diners" },
    { key: "storetype:food_court", label: "Food Court" },
    { key: "storetype:food_delivery_services", label: "Food Delivery Services" },
    { key: "storetype:food_trucks", label: "Food Trucks" },
    { key: "storetype:grocery", label: "Grocery" },
    { key: "storetype:juice_bars_smoothies", label: "Juice Bars & Smoothies" },
    { key: "storetype:meat_shops", label: "Meat Shops" },
    { key: "storetype:pasta_shops", label: "Pasta Shops" },
    { key: "storetype:pubs", label: "Pubs" },
    { key: "storetype:specialty_food", label: "Specialty Food" },
    { key: "storetype:sports_bars", label: "Sports Bars" },
    { key: "storetype:wineries", label: "Wineries" },
  ],
};

export async function GET() {
  return NextResponse.json({
    facets: [
      { key: "cuisine", label: "Cuisine", values: FACETS.cuisine },
      { key: "storetype", label: "Store Type", values: FACETS.storetype },
      { key: "activities", label: "Activities", values: FACETS.activities },
    ],
  });
}
